// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files.gtk (https://github.com/gtk-rs/gir-files)
// from gir-files.xfce
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) XFCE_LICENSE_TEXT_BSD);
    PRINT_CONSTANT((gint) XFCE_LICENSE_TEXT_GPL);
    PRINT_CONSTANT((gint) XFCE_LICENSE_TEXT_LGPL);
    PRINT_CONSTANT(XFCE_LOCALE_FULL_MATCH);
    PRINT_CONSTANT(XFCE_LOCALE_NO_MATCH);
    PRINT_CONSTANT((gint) XFCE_RESOURCE_CACHE);
    PRINT_CONSTANT((gint) XFCE_RESOURCE_CONFIG);
    PRINT_CONSTANT((gint) XFCE_RESOURCE_DATA);
    PRINT_CONSTANT((gint) XFCE_RESOURCE_ICONS);
    PRINT_CONSTANT((gint) XFCE_RESOURCE_THEMES);
    return 0;
}
