[package]
name = "libxfce4kbd-private-sys"
description = "FFI bindings to libxfce4kbd-private"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
build = "build.rs"
links = "xfce4kbd-private-3"
categories = [
    "external-ffi-bindings",
    "gui",
]

[package.metadata.system-deps.libxfce4kbd_private_3]
name = "libxfce4kbd-private-3"
version = "4.20"

[package.metadata.system-deps.libxfce4kbd_private_3.v4_21_4]
version = "4.21.4"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true
features = ["dox"]

[lib]
name = "libxfce4kbdprivate_sys"

[dependencies]
glib-sys.workspace = true
gobject-sys.workspace = true
gtk-sys.workspace = true
libc.workspace = true
libxfce4ui = { package = "libxfce4ui-sys", path = "../../libxfce4ui/sys", version = "0.2.2" }

[build-dependencies]
system-deps.workspace = true

[dev-dependencies]
shell-words.workspace = true
tempfile.workspace = true

[features]
dox = []
v4_21_4 = []
