[package]
name = "xfconf-sys"
description = "FFI bindings to libxfconf"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
build = "build.rs"
links = "xfconf-0"
categories = [
    "external-ffi-bindings",
    "gui",
]

[package.metadata.system-deps.libxfconf_0]
name = "libxfconf-0"
version = "4.20"

[package.metadata.system-deps.libxfconf_0.v4_21_1]
version = "4.21.1"

[package.metadata.system-deps.libxfconf_0.v4_21_2]
version = "4.21.2"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true
features = ["dox"]

[lib]
name = "xfconf_sys"

[dependencies]
glib-sys.workspace = true
gobject-sys.workspace = true
libc.workspace = true

[build-dependencies]
system-deps.workspace = true

[dev-dependencies]
shell-words.workspace = true
tempfile.workspace = true

[features]
dox = []
v4_21_1 = []
v4_21_2 = ["v4_21_1"]
