// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files.gtk (https://github.com/gtk-rs/gir-files)
// from gir-files.xfce
// DO NOT EDIT

mod consolekit;
pub use self::consolekit::Consolekit;

mod kiosk;
pub use self::kiosk::Kiosk;

mod systemd;
pub use self::systemd::Systemd;

pub(crate) mod functions;
