[workspace]
members = [
    "libxfce4kbd-private",
    "libxfce4kbd-private/sys",
    "libxfce4ui",
    "libxfce4ui/sys",
    "libxfce4util",
    "libxfce4util/sys",
    "xfconf",
    "xfconf/sys",
]
exclude = [
    "gir",
]
resolver = "2"

[workspace.package]
version = "0.3.0+dev"
license = "LGPL-2.1-only"
edition = "2024"
authors = [
    "Brian Tarricone <brian@tarricone.org>",
    "Andre Miranda <andreldm@xfce.org>",
]
homepage = "https://gitlab.xfce.org/bindings/xfce4-rs"
repository = "https://gitlab.xfce.org/bindings/xfce4-rs"
rust-version = "1.92.0"
keywords = [
    "api",
    "binding",
    "xfce",
]

[workspace.dependencies]
libxfce4kbd-private-sys = { path = "libxfce4kbd-private/sys", version = "0.3.0" }
libxfce4ui-sys = { path = "libxfce4ui/sys", version = "0.3.0" }
libxfce4util-sys = { path = "libxfce4util/sys", version = "0.3.0" }
xfce4-kbd-private = { path = "libxfce4kbd-private", version = "0.3.0" }
xfce4-ui = { path = "libxfce4ui", version = "0.3.0" }
xfce4-util = { path = "libxfce4util", version = "0.3.0" }
xfconf = { path = "xfconf", version = "0.3.0" }
xfconf-sys = { path = "xfconf/sys", version = "0.3.0" }

cairo-sys = { package = "cairo-sys-rs", version = "0.22" }
gdk-pixbuf-sys = "0.22"
gdk-sys = "0.19"
gio-sys = "0.22"
glib = "0.22"
glib-sys = "0.22"
gobject-sys = "0.22"
gtk-sys = "0.19"

bitflags = "2.2"
libc = "0.2"
regex = "1.10.4"
