// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files.gtk (https://github.com/gtk-rs/gir-files)
// from gir-files.xfce
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XfceConsolekitClass", sizeof(XfceConsolekitClass), alignof(XfceConsolekitClass));
    printf("%s;%zu;%zu\n", "XfceKioskClass", sizeof(XfceKioskClass), alignof(XfceKioskClass));
    printf("%s;%zu;%zu\n", "XfceLicenseTextType", sizeof(XfceLicenseTextType), alignof(XfceLicenseTextType));
    printf("%s;%zu;%zu\n", "XfceResourceType", sizeof(XfceResourceType), alignof(XfceResourceType));
    printf("%s;%zu;%zu\n", "XfceSystemdClass", sizeof(XfceSystemdClass), alignof(XfceSystemdClass));
    return 0;
}
