// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir-files.gtk
// from ../../gir-files.xfce
// DO NOT EDIT

#![cfg(unix)]

use libxfce4ui_sys::*;
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::mem::{align_of, size_of};
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["libxfce4ui-2"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG").unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!("Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",);
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "XfceCellRendererIconClass",
        Layout {
            size: size_of::<XfceCellRendererIconClass>(),
            alignment: align_of::<XfceCellRendererIconClass>(),
        },
    ),
    (
        "XfceClipboardManagerClass",
        Layout {
            size: size_of::<XfceClipboardManagerClass>(),
            alignment: align_of::<XfceClipboardManagerClass>(),
        },
    ),
    (
        "XfceGtkActionEntry",
        Layout {
            size: size_of::<XfceGtkActionEntry>(),
            alignment: align_of::<XfceGtkActionEntry>(),
        },
    ),
    (
        "XfceGtkMenuItem",
        Layout {
            size: size_of::<XfceGtkMenuItem>(),
            alignment: align_of::<XfceGtkMenuItem>(),
        },
    ),
    (
        "XfceIconChooserDialogClass",
        Layout {
            size: size_of::<XfceIconChooserDialogClass>(),
            alignment: align_of::<XfceIconChooserDialogClass>(),
        },
    ),
    (
        "XfceIconView",
        Layout {
            size: size_of::<XfceIconView>(),
            alignment: align_of::<XfceIconView>(),
        },
    ),
    (
        "XfceIconViewClass",
        Layout {
            size: size_of::<XfceIconViewClass>(),
            alignment: align_of::<XfceIconViewClass>(),
        },
    ),
    (
        "XfceIconViewDropPosition",
        Layout {
            size: size_of::<XfceIconViewDropPosition>(),
            alignment: align_of::<XfceIconViewDropPosition>(),
        },
    ),
    (
        "XfceIconViewLayoutMode",
        Layout {
            size: size_of::<XfceIconViewLayoutMode>(),
            alignment: align_of::<XfceIconViewLayoutMode>(),
        },
    ),
    (
        "XfceItemListModel",
        Layout {
            size: size_of::<XfceItemListModel>(),
            alignment: align_of::<XfceItemListModel>(),
        },
    ),
    (
        "XfceItemListModelClass",
        Layout {
            size: size_of::<XfceItemListModelClass>(),
            alignment: align_of::<XfceItemListModelClass>(),
        },
    ),
    (
        "XfceItemListModelColumn",
        Layout {
            size: size_of::<XfceItemListModelColumn>(),
            alignment: align_of::<XfceItemListModelColumn>(),
        },
    ),
    (
        "XfceItemListModelFlags",
        Layout {
            size: size_of::<XfceItemListModelFlags>(),
            alignment: align_of::<XfceItemListModelFlags>(),
        },
    ),
    (
        "XfceItemListStoreClass",
        Layout {
            size: size_of::<XfceItemListStoreClass>(),
            alignment: align_of::<XfceItemListStoreClass>(),
        },
    ),
    (
        "XfceItemListViewClass",
        Layout {
            size: size_of::<XfceItemListViewClass>(),
            alignment: align_of::<XfceItemListViewClass>(),
        },
    ),
    (
        "XfceItemListViewColumn",
        Layout {
            size: size_of::<XfceItemListViewColumn>(),
            alignment: align_of::<XfceItemListViewColumn>(),
        },
    ),
    (
        "XfceNotebookClass",
        Layout {
            size: size_of::<XfceNotebookClass>(),
            alignment: align_of::<XfceNotebookClass>(),
        },
    ),
    (
        "XfceSMClientPriority",
        Layout {
            size: size_of::<XfceSMClientPriority>(),
            alignment: align_of::<XfceSMClientPriority>(),
        },
    ),
    (
        "XfceSMClientRestartStyle",
        Layout {
            size: size_of::<XfceSMClientRestartStyle>(),
            alignment: align_of::<XfceSMClientRestartStyle>(),
        },
    ),
    (
        "XfceSMClientShutdownHint",
        Layout {
            size: size_of::<XfceSMClientShutdownHint>(),
            alignment: align_of::<XfceSMClientShutdownHint>(),
        },
    ),
    (
        "XfceScreensaverClass",
        Layout {
            size: size_of::<XfceScreensaverClass>(),
            alignment: align_of::<XfceScreensaverClass>(),
        },
    ),
    (
        "XfceSmCLientErrorEnum",
        Layout {
            size: size_of::<XfceSmCLientErrorEnum>(),
            alignment: align_of::<XfceSmCLientErrorEnum>(),
        },
    ),
    (
        "XfceTitledDialog",
        Layout {
            size: size_of::<XfceTitledDialog>(),
            alignment: align_of::<XfceTitledDialog>(),
        },
    ),
    (
        "XfceTitledDialogClass",
        Layout {
            size: size_of::<XfceTitledDialogClass>(),
            alignment: align_of::<XfceTitledDialogClass>(),
        },
    ),
    (
        "XfceTreeViewClass",
        Layout {
            size: size_of::<XfceTreeViewClass>(),
            alignment: align_of::<XfceTreeViewClass>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("XFCE_BUTTON_TYPE_MIXED", "button-mixed"),
    ("XFCE_BUTTON_TYPE_PIXBUF", "button-pixbuf"),
    ("(gint) XFCE_GTK_CHECK_MENU_ITEM", "2"),
    ("(gint) XFCE_GTK_IMAGE_MENU_ITEM", "1"),
    ("(gint) XFCE_GTK_MENU_ITEM", "0"),
    ("(gint) XFCE_GTK_RADIO_MENU_ITEM", "3"),
    ("(gint) XFCE_ICON_VIEW_DROP_ABOVE", "4"),
    ("(gint) XFCE_ICON_VIEW_DROP_BELOW", "5"),
    ("(gint) XFCE_ICON_VIEW_DROP_INTO", "1"),
    ("(gint) XFCE_ICON_VIEW_DROP_LEFT", "2"),
    ("(gint) XFCE_ICON_VIEW_DROP_RIGHT", "3"),
    ("(gint) XFCE_ICON_VIEW_LAYOUT_COLS", "1"),
    ("(gint) XFCE_ICON_VIEW_LAYOUT_ROWS", "0"),
    ("(gint) XFCE_ICON_VIEW_NO_DROP", "0"),
    ("(guint) XFCE_ITEM_LIST_MODEL_ADDABLE", "2"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_ACTIVABLE", "1"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_ACTIVE", "0"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_EDITABLE", "5"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_ICON", "2"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_NAME", "3"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_REMOVABLE", "6"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_TOOLTIP", "4"),
    ("(gint) XFCE_ITEM_LIST_MODEL_COLUMN_USER", "7"),
    ("(guint) XFCE_ITEM_LIST_MODEL_EDITABLE", "8"),
    ("(guint) XFCE_ITEM_LIST_MODEL_NONE", "0"),
    ("(guint) XFCE_ITEM_LIST_MODEL_REMOVABLE", "4"),
    ("(guint) XFCE_ITEM_LIST_MODEL_REORDERABLE", "1"),
    ("(guint) XFCE_ITEM_LIST_MODEL_RESETTABLE", "16"),
    ("(gint) XFCE_ITEM_LIST_VIEW_COLUMN_ACTIVE", "0"),
    ("(gint) XFCE_ITEM_LIST_VIEW_COLUMN_ICON", "1"),
    ("(gint) XFCE_ITEM_LIST_VIEW_COLUMN_NAME", "2"),
    ("(gint) XFCE_ITEM_LIST_VIEW_COLUMN_USER", "3"),
    ("XFCE_MENU_ATTRIBUTE_HIDE_IN_BUTTONS", "hide-in-buttons"),
    (
        "XFCE_MENU_ATTRIBUTE_HIDE_IN_CONTEXT_MENU",
        "hide-in-context-menu",
    ),
    ("XFCE_MENU_ATTRIBUTE_MOVEMENT", "movement"),
    ("XFCE_MENU_ATTRIBUTE_TOOLTIP", "tooltip"),
    ("(gint) XFCE_SM_CLIENT_ERROR_FAILED", "0"),
    ("(gint) XFCE_SM_CLIENT_ERROR_INVALID_CLIENT", "1"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_CORE", "25"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_DEFAULT", "50"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_DESKTOP", "35"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_HIGHEST", "0"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_LOWEST", "255"),
    ("(gint) XFCE_SM_CLIENT_PRIORITY_WM", "15"),
    ("(gint) XFCE_SM_CLIENT_RESTART_IMMEDIATELY", "1"),
    ("(gint) XFCE_SM_CLIENT_RESTART_NORMAL", "0"),
    ("(gint) XFCE_SM_CLIENT_SHUTDOWN_HINT_ASK", "0"),
    ("(gint) XFCE_SM_CLIENT_SHUTDOWN_HINT_HALT", "2"),
    ("(gint) XFCE_SM_CLIENT_SHUTDOWN_HINT_LOGOUT", "1"),
    ("(gint) XFCE_SM_CLIENT_SHUTDOWN_HINT_REBOOT", "3"),
];
