// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir-files.gtk
// from ../../gir-files.xfce
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XfceCellRendererIconClass", sizeof(XfceCellRendererIconClass), alignof(XfceCellRendererIconClass));
    printf("%s;%zu;%zu\n", "XfceClipboardManagerClass", sizeof(XfceClipboardManagerClass), alignof(XfceClipboardManagerClass));
    printf("%s;%zu;%zu\n", "XfceGtkActionEntry", sizeof(XfceGtkActionEntry), alignof(XfceGtkActionEntry));
    printf("%s;%zu;%zu\n", "XfceGtkMenuItem", sizeof(XfceGtkMenuItem), alignof(XfceGtkMenuItem));
    printf("%s;%zu;%zu\n", "XfceIconChooserDialogClass", sizeof(XfceIconChooserDialogClass), alignof(XfceIconChooserDialogClass));
    printf("%s;%zu;%zu\n", "XfceIconView", sizeof(XfceIconView), alignof(XfceIconView));
    printf("%s;%zu;%zu\n", "XfceIconViewClass", sizeof(XfceIconViewClass), alignof(XfceIconViewClass));
    printf("%s;%zu;%zu\n", "XfceIconViewDropPosition", sizeof(XfceIconViewDropPosition), alignof(XfceIconViewDropPosition));
    printf("%s;%zu;%zu\n", "XfceIconViewLayoutMode", sizeof(XfceIconViewLayoutMode), alignof(XfceIconViewLayoutMode));
    printf("%s;%zu;%zu\n", "XfceItemListModel", sizeof(XfceItemListModel), alignof(XfceItemListModel));
    printf("%s;%zu;%zu\n", "XfceItemListModelClass", sizeof(XfceItemListModelClass), alignof(XfceItemListModelClass));
    printf("%s;%zu;%zu\n", "XfceItemListModelColumn", sizeof(XfceItemListModelColumn), alignof(XfceItemListModelColumn));
    printf("%s;%zu;%zu\n", "XfceItemListModelFlags", sizeof(XfceItemListModelFlags), alignof(XfceItemListModelFlags));
    printf("%s;%zu;%zu\n", "XfceItemListStoreClass", sizeof(XfceItemListStoreClass), alignof(XfceItemListStoreClass));
    printf("%s;%zu;%zu\n", "XfceItemListViewClass", sizeof(XfceItemListViewClass), alignof(XfceItemListViewClass));
    printf("%s;%zu;%zu\n", "XfceItemListViewColumn", sizeof(XfceItemListViewColumn), alignof(XfceItemListViewColumn));
    printf("%s;%zu;%zu\n", "XfceNotebookClass", sizeof(XfceNotebookClass), alignof(XfceNotebookClass));
    printf("%s;%zu;%zu\n", "XfceSMClientPriority", sizeof(XfceSMClientPriority), alignof(XfceSMClientPriority));
    printf("%s;%zu;%zu\n", "XfceSMClientRestartStyle", sizeof(XfceSMClientRestartStyle), alignof(XfceSMClientRestartStyle));
    printf("%s;%zu;%zu\n", "XfceSMClientShutdownHint", sizeof(XfceSMClientShutdownHint), alignof(XfceSMClientShutdownHint));
    printf("%s;%zu;%zu\n", "XfceScreensaverClass", sizeof(XfceScreensaverClass), alignof(XfceScreensaverClass));
    printf("%s;%zu;%zu\n", "XfceSmCLientErrorEnum", sizeof(XfceSmCLientErrorEnum), alignof(XfceSmCLientErrorEnum));
    printf("%s;%zu;%zu\n", "XfceTitledDialog", sizeof(XfceTitledDialog), alignof(XfceTitledDialog));
    printf("%s;%zu;%zu\n", "XfceTitledDialogClass", sizeof(XfceTitledDialogClass), alignof(XfceTitledDialogClass));
    printf("%s;%zu;%zu\n", "XfceTreeViewClass", sizeof(XfceTreeViewClass), alignof(XfceTreeViewClass));
    return 0;
}
