[options]
library = "Libxfce4util"
version = "1.0"
min_cfg_version = "4.18"
target_path = "."
girs_directories = [
    "../gir-files.xfce/",
    "../gir-files.gtk/",
]
work_mode = "sys"
single_version_file = true
external_libraries = [
    "Gio",
    "Glib",
    "GObject",
]
