// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir-files.gtk
// from ../../gir-files.xfce
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XfceShortcut", sizeof(XfceShortcut), alignof(XfceShortcut));
    printf("%s;%zu;%zu\n", "XfceShortcutsEditorSection", sizeof(XfceShortcutsEditorSection), alignof(XfceShortcutsEditorSection));
    printf("%s;%zu;%zu\n", "XfceShortcutsGrabber", sizeof(XfceShortcutsGrabber), alignof(XfceShortcutsGrabber));
    printf("%s;%zu;%zu\n", "XfceShortcutsGrabberClass", sizeof(XfceShortcutsGrabberClass), alignof(XfceShortcutsGrabberClass));
    printf("%s;%zu;%zu\n", "XfceShortcutsProvider", sizeof(XfceShortcutsProvider), alignof(XfceShortcutsProvider));
    printf("%s;%zu;%zu\n", "XfceShortcutsProviderClass", sizeof(XfceShortcutsProviderClass), alignof(XfceShortcutsProviderClass));
    return 0;
}
