[package]
name = "xfconf"
description = "Provides access to xfconf, Xfce's desktop configuration system"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "api-bindings",
    "gui",
]

[package.metadata.docs.rs]
all-features = true
# For build.rs scripts
rustc-args = ["--cfg", "docsrs"]
# For rustdoc
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags.workspace = true
ffi = { package = "xfconf-sys", path = "sys", version = "0.1.0-dev" }
glib.workspace = true
libc.workspace = true

[features]
v4_21_1 = ["ffi/v4_21_1"]
v4_21_2 = ["v4_21_1", "ffi/v4_21_2"]
