[package]
name = "xfce4-ui"
description = "Xfce UI utility library"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "api-bindings",
    "gui",
]

[dependencies]
ffi = { package = "libxfce4ui-sys", path = "sys", version = "0.2.0" }

[features]
dox = []
v4_21 = ["ffi/v4_21"]
v4_21_1 = ["ffi/v4_21_1", "v4_21"]
v4_21_3 = ["ffi/v4_21_3", "v4_21_1"]
v4_21_4 = ["ffi/v4_21_4", "v4_21_3"]
