[package]
name = "xfce4-ui"
description = "Xfce UI utility library"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "api-bindings",
    "gui",
]

[dependencies]
libxfce4ui-sys.workspace = true

[features]
dox = []
v4_21 = ["libxfce4ui-sys/v4_21"]
v4_21_1 = ["libxfce4ui-sys/v4_21_1", "v4_21"]
v4_21_3 = ["libxfce4ui-sys/v4_21_3", "v4_21_1"]
v4_21_4 = ["libxfce4ui-sys/v4_21_4", "v4_21_3"]
