[package]
name = "xfce4-kbd-private"
description = "Bindings for the private Xfce keyboard library (not for use outside Xfce components)"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "api-bindings",
    "gui",
]

[package.metadata.docs.rs]
all-features = true
# For build.rs scripts
rustc-args = ["--cfg", "docsrs"]
# For rustdoc
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.system-deps.libxfce4kbd_private_3.v4_21_4]
name = "libxfce4kbd-private-3"
version = "4.21.4"

[dependencies]
bitflags.workspace = true
ffi = { package = "libxfce4kbd-private-sys", path = "sys", version = "0.1.1-dev" }
glib.workspace = true
libc.workspace = true

[dev-dependencies]
regex.workspace = true

[features]
v4_21_4 = ["ffi/v4_21_4"]
