// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files.gtk (https://github.com/gtk-rs/gir-files)
// from gir-files.xfce
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) XFCONF_ERROR_CHANNEL_NOT_FOUND);
    PRINT_CONSTANT((gint) XFCONF_ERROR_INTERNAL_ERROR);
    PRINT_CONSTANT((gint) XFCONF_ERROR_INVALID_CHANNEL);
    PRINT_CONSTANT((gint) XFCONF_ERROR_INVALID_PROPERTY);
    PRINT_CONSTANT((gint) XFCONF_ERROR_NO_BACKEND);
    PRINT_CONSTANT((gint) XFCONF_ERROR_PERMISSION_DENIED);
    PRINT_CONSTANT((gint) XFCONF_ERROR_PROPERTY_NOT_FOUND);
    PRINT_CONSTANT((gint) XFCONF_ERROR_READ_FAILURE);
    PRINT_CONSTANT((gint) XFCONF_ERROR_UNKNOWN);
    PRINT_CONSTANT((gint) XFCONF_ERROR_WRITE_FAILURE);
    return 0;
}
