[package]
name = "xfce4-util"
description = "Xfce utility library"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "api-bindings",
    "gui",
]

[package.metadata.docs.rs]
all-features = true
# For build.rs scripts
rustc-args = ["--cfg", "docsrs"]
# For rustdoc
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags.workspace = true
ffi = { package = "libxfce4util-sys", path = "sys", version = "0.1.1-dev" }
glib.workspace = true
libc.workspace = true

[dev-dependencies]
regex.workspace = true
