// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files.gtk
// from ../gir-files.xfce
// DO NOT EDIT

mod shortcuts_provider;
pub use self::shortcuts_provider::ShortcutsProvider;

mod shortcut;
pub use self::shortcut::Shortcut;

pub(crate) mod traits {
    pub use super::shortcuts_provider::ShortcutsProviderExt;
}
