// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files.gtk
// from ../gir-files.xfce
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Shortcut(Boxed<ffi::XfceShortcut>);

    match fn {
        copy => |ptr| ffi::xfce_shortcut_copy(mut_override(ptr)),
        free => |ptr| ffi::xfce_shortcut_free(ptr),
        type_ => || ffi::xfce_shortcut_get_type(),
    }
}

impl Shortcut {
    //#[doc(alias = "xfce_shortcut_conflict_dialog")]
    //pub fn conflict_dialog(parent: /*Ignored*/&gtk::Window, owner: &str, other: &str, shortcut: &str, owner_action: &str, other_action: &str, ignore_same_provider: bool) -> bool {
    //    unsafe { TODO: call ffi:xfce_shortcut_conflict_dialog() }
    //}
}
