[package]
name = "libxfce4ui-sys"
description = "FFI bindings to libxfce4ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
build = "build.rs"
links = "xfce4ui-2"
categories = [
    "external-ffi-bindings",
    "gui",
]

[package.metadata.system-deps.libxfce4ui_2]
name = "libxfce4ui-2"
version = "4.20"

[package.metadata.system-deps.libxfce4ui_2.v4_21]
version = "4.21"

[package.metadata.system-deps.libxfce4ui_2.v4_21_1]
version = "4.21.1"

[package.metadata.system-deps.libxfce4ui_2.v4_21_3]
version = "4.21.3"

[package.metadata.system-deps.libxfce4ui_2.v4_21_4]
version = "4.21.4"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true
features = ["dox"]

[lib]
name = "libxfce4ui_sys"

[dependencies]
cairo.workspace = true
gdk-pixbuf.workspace = true
gdk-sys.workspace = true
gio-sys.workspace = true
glib-sys.workspace = true
gobject-sys.workspace = true
gtk-sys.workspace = true
libc.workspace = true

[build-dependencies]
system-deps.workspace = true

[dev-dependencies]
shell-words.workspace = true
tempfile.workspace = true

[features]
dox = []
v4_21 = []
v4_21_1 = ["v4_21"]
v4_21_3 = ["v4_21_1"]
v4_21_4 = ["v4_21_3"]
