[package]
name = "libxfce4ui-sys"
description = "FFI bindings to libxfce4ui"
build = "build.rs"
links = "xfce4ui-2"
categories = ["external-ffi-bindings", "gui"]

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.keywords]
workspace = true

[package.metadata.system-deps.libxfce4ui_2]
name = "libxfce4ui-2"
version = "4.20"

[package.metadata.system-deps.libxfce4ui_2.v4_21]
version = "4.21"

[package.metadata.system-deps.libxfce4ui_2.v4_21_1]
version = "4.21.1"

[package.metadata.system-deps.libxfce4ui_2.v4_21_3]
version = "4.21.3"

[package.metadata.system-deps.libxfce4ui_2.v4_21_4]
version = "4.21.4"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true
features = ["dox"]

[lib]
name = "libxfce4ui_sys"

[dependencies]
libc = "0.2"

[dependencies.cairo]
workspace = true

[dependencies.gdk-pixbuf]
workspace = true

[dependencies.gdk-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.gtk-sys]
workspace = true

[build-dependencies]
system-deps = "9"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []
v4_21 = []
v4_21_1 = ["v4_21"]
v4_21_3 = ["v4_21_1"]
v4_21_4 = ["v4_21_3"]
